
import { GoogleGenAI } from "@google/genai";
import { AspectRatio, ImageSize, ModelType } from "../types";

export class GeminiService {
  private static getClient() {
    return new GoogleGenAI({ apiKey: process.env.API_KEY });
  }

  static async generateWallpaper(params: {
    prompt: string;
    aspectRatio: AspectRatio;
    model: ModelType;
    imageSize?: ImageSize;
  }): Promise<string> {
    const ai = this.getClient();
    
    try {
      const response = await ai.models.generateContent({
        model: params.model,
        contents: {
          parts: [{ text: params.prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: params.aspectRatio,
            ...(params.imageSize && { imageSize: params.imageSize }),
          },
        },
      });

      // Find the image part in the response
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }

      throw new Error("No image was generated by the model.");
    } catch (error: any) {
      console.error("Gemini Generation Error:", error);
      throw error;
    }
  }
}
